### ISSUE TITLE
Only one GPU was used!

### ISSUE THREAD

**Issue by ylxuer** [luofuli/word-sense-disambiguation#1]
I have tried GAS.train for twice, but the same problem is only one gpu is used, even though I set all GPUs can be used. Is this really the case? Or what changes should I make?

**Comment by luofuli** [comment]
Yes, our code doesn't support multi-GPUs. But our code will request nearly all of the GPU memory of all GPUs to avoid memory fragmentation (since GPU has much less memory, it is more vulnerable to fragmentation). If you want to support multi-GPUs, see this [example](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py).

**Comment by ylxuer** [comment]
Luoli：
       收到啦~谢谢！

**Comment by ylxuer** [comment]
OK, thank you very much!
